In [53]:
import sys
sys.path.append("..")
import pickle
import cv2
import matplotlib.pyplot as plt
from mvt.utils import draw_boxes, draw_motion_vectors
import seaborn as sns
import numpy as np
import math
import torch

In [54]:
motion_vectors = pickle.load(open("motion_vectors.pkl", "rb"))

In [55]:
motion_vectors.shape

(7526, 10)

In [72]:
def motion_vectors_to_grid(motion_vectors, frame_shape=(1920, 1080)):
    motion_vectors_grid = np.zeros((2, math.ceil(frame_shape[1]/16), math.ceil(frame_shape[0]/16)))
    mvs_x = motion_vectors[:, 5] 
    mvs_y = motion_vectors[:, 6]
    x = (mvs_x - 8) // 16
    y = (mvs_y - 8) // 16
    motion_vectors_grid[0, y, x] = motion_vectors[:, 7] / motion_vectors[:, 9]  # x component
    motion_vectors_grid[1, y, x] = motion_vectors[:, 8] / motion_vectors[:, 9] # y component
    return motion_vectors_grid

In [73]:
motion_vectors_grid = motion_vectors_to_grid(motion_vectors)
motion_vectors_grid = torch.from_numpy(motion_vectors_grid)
motion_vectors_grid.shape

torch.Size([2, 68, 120])

In [87]:
motion_vectors_grid[:, 1, 0]

tensor([12.,  7.], dtype=torch.float64)

In [68]:
for motion_vector in motion_vectors:
    print(motion_vector)

[-1 16 16  0  8  8  8 16  0  2]
[-1 16 16 16  8 24  8 16  0  2]
[-1 16 16 40  7 56  8 32  2  2]
[-1 16 16 57  4 72  8 31  9  2]
[-1 16 16 88  0 88  8  1 17  2]
[ -1  16  16 104   8 104   8   0   1   2]
[ -1  16  16 104   4 120   8  32   9   2]
[ -1  16  16 104   7 136   8  64   2   2]
[ -1  16  16 128   6 152   8  48   5   2]
[ -1  16  16 160   0 184   8  48  16   2]
[ -1  16  16 168   0 200   8  64  16   2]
[ -1  16  16 264   2 264   8   1  13   2]
[ -1  16  16 280   1 280   8   0  14   2]
[ -1  16  16 312   0 296   8 -32  16   2]
[ -1  16  16 312   6 312   8   1   5   2]
[ -1  16  16 329   5 328   8  -2   6   2]
[ -1  16  16 344   0 344   8   0  16   2]
[ -1  16  16 361   6 360   8  -3   5   2]
[ -1  16  16 377   8 376   8  -2   1   2]
[ -1  16  16 392   0 392   8   0  16   2]
[ -1  16  16 408   0 408   8  -1  17   2]
[ -1  16  16 424   5 424   8   0   7   2]
[ -1  16  16 440   8 440   8   0   0   2]
[ -1  16  16 457  12 456   8  -2  -8   2]
[ -1  16  16 472   8 472   8   0   0   2]
